version: "3.5"

services:
  test-throughput:
    build:
      context: .
    image: test-throughput
    # container_name: test-throughput
    platform: linux/amd64
    restart: always
    ports:
      - "3000"
    env_file:
      - .env
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 256M

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    env_file:
      - .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test-throughput
    ports:
      - "4000:4000"
